# Generated by Django 5.2.6 on 2025-09-16 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_text', models.TextField(help_text='Original English text to translate')),
                ('khmer_text', models.TextField(help_text='Translated Khmer text')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the translation was performed')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
