# Generated by Django 5.2.6 on 2025-09-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='accuracy_percentage',
            field=models.FloatField(default=0.0, help_text='Translation accuracy as percentage (0.0 to 100.0)'),
        ),
        migrations.AddField(
            model_name='translation',
            name='confidence_score',
            field=models.FloatField(default=0.0, help_text='Translation confidence score (0.0 to 1.0)'),
        ),
    ]
